# Generated by Django 3.1.6 on 2021-02-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('compny_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('rate', models.FloatField()),
                ('record', models.DateField()),
                ('ex_devedend', models.DateField()),
                ('dividend_fv', models.FloatField()),
                ('dividend_mp', models.FloatField()),
            ],
        ),
    ]
