# Generated by Django 3.1.6 on 2021-02-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devedend_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='announcment',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
