# Generated by Django 3.1.6 on 2021-02-26 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devedend_data', '0002_data_announcment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='announcment',
        ),
    ]
