# Generated by Django 3.1.6 on 2021-02-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devedend_data', '0003_remove_data_announcment'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='announcment',
            field=models.DateField(default=-2020),
            preserve_default=False,
        ),
    ]
